// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO64nmphpXcfTA-xEl9_jYWRlVs_8zTVE',
    appId: '1:746323217658:web:5683fa3ec7a08b625d4d43',
    messagingSenderId: '746323217658',
    projectId: 'sanatan-scroll-19b25',
    authDomain: 'sanatan-scroll-19b25.firebaseapp.com',
    storageBucket: 'sanatan-scroll-19b25.firebasestorage.app',
    measurementId: 'G-GW23F2BJW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgdzgYurf4TzOA4iNRNPCMK2y7xhlKjFc',
    appId: '1:746323217658:android:05599e93219860775d4d43',
    messagingSenderId: '746323217658',
    projectId: 'sanatan-scroll-19b25',
    storageBucket: 'sanatan-scroll-19b25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY3O896ojXhnKWVWchonXLlO5q1ZI1Qss',
    appId: '1:746323217658:ios:0ef55f1e5838d8455d4d43',
    messagingSenderId: '746323217658',
    projectId: 'sanatan-scroll-19b25',
    storageBucket: 'sanatan-scroll-19b25.firebasestorage.app',
    iosBundleId: 'com.sanatanscroll.sanatanScroll',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO64nmphpXcfTA-xEl9_jYWRlVs_8zTVE',
    appId: '1:746323217658:web:d735e9a9302bed375d4d43',
    messagingSenderId: '746323217658',
    projectId: 'sanatan-scroll-19b25',
    authDomain: 'sanatan-scroll-19b25.firebaseapp.com',
    storageBucket: 'sanatan-scroll-19b25.firebasestorage.app',
    measurementId: 'G-JV2W2PW7JS',
  );
}
